<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

function hello_menu_menu() {
  $items = array();
  
  $items['hello'] = array(
    'title' => 'Hello World',
    'page callback' => 'hello_menu_simple_hello',
    'access arguments' => array('access content'),
    'menu_name' => 'main-menu',
    'weight' => 1,
    );  
  
  $items['variables'] = array(
    'title' => 'Hello Variables',
    'page callback' => 'hello_menu_list_variables',
    'access arguments' => array('access content'),
    'menu_name' => 'main-menu',
    'weight' => 2,
    );
  
  return $items;
}

function hello_menu_list_variables() {
  $variables = variable_initialize();
  $names = array_keys($variables);
  $output = '<ul>';
  foreach ($names as $name) {
    $output .= '<li>' . $name . '</li>';
  }
  $output .= '</ul>';
  return ($output);
}

function hello_menu_simple_hello() {
  return t('Hello world!!');
}